services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 

    container_name: analyzer-frontend

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app/monitoring-app

    env_file:
      - ./frontend/.env

    networks:
      - edinet-analyzer-network

    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      
    container_name: analyzer-backend

    ports:
      - "8080:8080"

    volumes: 
      - ./backend:/app

    env_file:
      - ./backend/.env

    # mysqlの後に起動するらしい
    # depends_on:
    #   - mysql

    networks:
      - edinet-analyzer-network

    tty: true

    # コマンドを実行できるようにするやつらしい
    stdin_open: true

networks:
  edinet-analyzer-network: