services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 

    container_name: analyzer-frontend

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app/monitoring-app

    env_file:
      - ./frontend/.env

    networks:
      - edinet-analyzer-network

    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      
    container_name: analyzer-backend

    ports:
      - "8080:8080"

    volumes: 
      - ./backend:/app

    env_file:
      - ./backend/.env

    # mysqlの後に起動するらしい
    depends_on:
      - mysql

    networks:
      - edinet-analyzer-network

    tty: true

    # コマンドを実行できるようにするやつらしい
    stdin_open: true

  mysql:
    image: mysql:8.0

    container_name: edinet-mysql

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: edinet_analyzer_db
      MYSQL_USER: analyzer_user
      MYSQL_PASSWORD: analyzer_password

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - edinet-analyzer-network

volumes:
  mysql-data:

networks:
  edinet-analyzer-network: